import numpy as np

# Trader params
STOCK_TICKER = 'AMC'
INIT_CASH = 1000.0

AFTER_HOURS_SLEEP = 60
TRADING_HOURS_SLEEP = 2
PREDICTION_INTERVAL = 60

CLIENT_TYPE = 'ALPACA' # ETRADE / ALPACA
MODEL_TYPE = 'TF' # TF / TORCH

MODE = 'SANDBOX' # PRODUCTION / SANDBOX


# Data params
NUM_FEATURES = 4 
NUM_WEEKS = 3
UNITS = 'm'
INTERVAL_UNITS = 1
INTERVAL = str(INTERVAL_UNITS) + UNITS
POINTS_PER_PERIOD = 10
LABEL_FUNC = lambda x: np.mean(x[0])


# Model training params
if MODEL_TYPE == 'TF':
	MAX_EPOCHS = 100
	PATIENCE = 2
	TRAINING_SET_THRESH = 0.85

	C_DIFF_SIGN = 0.5
	C_SAME_SIGN = 0.1

elif MODEL_TYPE == 'TORCH':
	MAX_EPOCHS = 20
	PATIENCE = 2
	TRAINING_SET_THRESH = 0.85
	LEARNING_RATE = 1e-3
	MOMENTUM = 0.95
	USE_GPU = True
	PRINT_EVERY = 100

	C_DIFF_SIGN = 0.5
	C_SAME_SIGN = 0.1